# Site settings
title: sumstock
description: スムストックからデータを取得します
baseurl: "/sumstock"
url: "https://zGVfRcgR.github.io"

# Theme settings
remote_theme: just-the-docs/just-the-docs

# Exclude theme files from build  
exclude:
  - CHANGELOG.md
  - MIGRATION.md
  - CODE_OF_CONDUCT.md
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/
  - node_modules/
  - package.json
  - package-lock.json
  - Rakefile
  - just-the-docs.gemspec

# Just the Docs specific settings
# Enable or disable the site search
search_enabled: true

# Enable support for mermaid diagrams
mermaid:
  version: "9.1.3"

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "https://github.com/zGVfRcgR/sumstock"

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2025. Distributed by an <a href=\"https://github.com/zGVfRcgR/sumstock/tree/main/LICENSE\">MIT license.</a>"

# Color scheme supports "light" (default) and "dark"
color_scheme: light

# Google Analytics Tracking (optional)
ga_tracking: G-H4R3F2S52Z

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
