apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sumstock-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/zGVfRcgR/sumstock.git'
    targetRevision: HEAD
    path: k8s/app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
